name: Run Python Script Daily

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  execute_script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Checks out a copy of your repository.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      # Sets up a Python environment.

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
      # Installs Google Chrome.

    - name: Install ChromeDriver and Selenium
      run: |
        sudo apt-get install -yqq unzip
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
      # Installs ChromeDriver and Selenium.

    - name: Run Python script and update JSON
      run: python coupons_collect.py
      # Runs your script.

    - name: Commit and Push if Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions Bot"
        git add all_coupon_data.json
        git commit -m "Updated JSON data" || echo "No changes to commit"
        git push
      # This step commits and pushes the updated JSON file back to the repository.
